"""update tables1

Revision ID: 48f0789d1660
Revises: 6a58677acba4
Create Date: 2023-04-25 18:14:10.180582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f0789d1660'
down_revision = '6a58677acba4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_planner', sa.Column('idEntry', sa.UUID(), nullable=False))
    op.drop_column('daily_planner', 'idTaskInCard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_planner', sa.Column('idTaskInCard', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('daily_planner', 'idEntry')
    # ### end Alembic commands ###
