"""update tables6

Revision ID: 823552d7b6dc
Revises: f5d42566a905
Create Date: 2023-05-22 18:31:49.054295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823552d7b6dc'
down_revision = 'f5d42566a905'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_list',
    sa.Column('idTaskInList', sa.UUID(), nullable=False),
    sa.Column('textOfItem', sa.String(), nullable=False),
    sa.Column('isChecked', sa.Boolean(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('update_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idTaskInList')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks_list')
    # ### end Alembic commands ###
