"""update tables4

Revision ID: 8392c3ec18dc
Revises: c4af3745b692
Create Date: 2023-05-01 15:42:27.684889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8392c3ec18dc'
down_revision = 'c4af3745b692'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gantt_task_duration_idGanttDuration_key', 'gantt_task_duration', type_='unique')
    op.drop_constraint('gantt_tasks_idGanttTask_key', 'gantt_tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('gantt_tasks_idGanttTask_key', 'gantt_tasks', ['idGanttTask'])
    op.create_unique_constraint('gantt_task_duration_idGanttDuration_key', 'gantt_task_duration', ['idGanttDuration'])
    # ### end Alembic commands ###
