"""update tables5

Revision ID: 83e154e4054c
Revises: 8392c3ec18dc
Create Date: 2023-05-01 15:49:25.351737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e154e4054c'
down_revision = '8392c3ec18dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
