"""create kanban tables

Revision ID: 876f8cf2ab2c
Revises: 9c92ba8e8339
Create Date: 2023-04-06 15:33:23.351384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876f8cf2ab2c'
down_revision = '9c92ba8e8339'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards_type',
    sa.Column('id_type', sa.UUID(), nullable=False),
    sa.Column('typeName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_type'),
    sa.UniqueConstraint('typeName')
    )
    op.create_table('task_kanban',
    sa.Column('id_task', sa.UUID(), nullable=False),
    sa.Column('taskName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_task')
    )
    op.create_table('kanban_cards',
    sa.Column('id_card', sa.UUID(), nullable=False),
    sa.Column('typeOfCard', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['typeOfCard'], ['cards_type.id_type'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_card')
    )
    op.create_table('task_in_cards',
    sa.Column('id_task_in_card', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['kanban_cards.id_card'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task_kanban.id_task'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_task_in_card')
    )
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('verified', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'users', ['verification_code'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'verified')
    op.drop_column('users', 'email')
    op.drop_table('task_in_cards')
    op.drop_table('kanban_cards')
    op.drop_table('task_kanban')
    op.drop_table('cards_type')
    # ### end Alembic commands ###
