"""update tables8

Revision ID: 8b22ab729d19
Revises: 2e11831b3d60
Create Date: 2023-05-25 23:03:40.073172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b22ab729d19'
down_revision = '2e11831b3d60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technics_settings',
    sa.Column('idTechnic', sa.UUID(), nullable=False),
    sa.Column('settingsName', sa.String(), nullable=False),
    sa.Column('workTimer', sa.Integer(), nullable=False),
    sa.Column('shortBreak', sa.Integer(), nullable=False),
    sa.Column('longBreak', sa.Integer(), nullable=False),
    sa.Column('countOfCycles', sa.Integer(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('update_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idTechnic')
    )
    op.drop_column('daily_planner', 'taskStatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_planner', sa.Column('taskStatus', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('technics_settings')
    # ### end Alembic commands ###
