"""update tables2

Revision ID: a6ccd7b4c44b
Revises: 48f0789d1660
Create Date: 2023-04-27 15:43:38.831219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ccd7b4c44b'
down_revision = '48f0789d1660'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
