"""update tables3

Revision ID: c4af3745b692
Revises: a6ccd7b4c44b
Create Date: 2023-04-27 16:41:47.782940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4af3745b692'
down_revision = 'a6ccd7b4c44b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gantt_task_duration', sa.Column('idGanttDuration', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('gantt_task_duration', sa.Column('ganttTaskId', sa.Integer(), nullable=False))
    op.drop_constraint('gantt_task_duration_idGanttTask_key', 'gantt_task_duration', type_='unique')
    op.create_unique_constraint(None, 'gantt_task_duration', ['idGanttDuration'])
    op.drop_constraint('gantt_task_duration_projectId_fkey', 'gantt_task_duration', type_='foreignkey')
    op.create_foreign_key(None, 'gantt_task_duration', 'gantt_tasks', ['ganttTaskId'], ['idGanttTask'], ondelete='CASCADE')
    op.drop_column('gantt_task_duration', 'idGanttTask')
    op.drop_column('gantt_task_duration', 'projectId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gantt_task_duration', sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('gantt_task_duration', sa.Column('idGanttTask', sa.INTEGER(), server_default=sa.text('nextval(\'"gantt_task_duration_idGanttTask_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'gantt_task_duration', type_='foreignkey')
    op.create_foreign_key('gantt_task_duration_projectId_fkey', 'gantt_task_duration', 'gantt_tasks', ['projectId'], ['idGanttTask'], ondelete='CASCADE')
    op.drop_constraint(None, 'gantt_task_duration', type_='unique')
    op.create_unique_constraint('gantt_task_duration_idGanttTask_key', 'gantt_task_duration', ['idGanttTask'])
    op.drop_column('gantt_task_duration', 'ganttTaskId')
    op.drop_column('gantt_task_duration', 'idGanttDuration')
    # ### end Alembic commands ###
